version: '3.8'

services:
  back:
    build:
      context: ./back
    volumes:
      - ./back:/usr/src/app
      - ./back/data:/usr/src/app/data
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true

  front:
    build:
      context: ./front
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true