version: '3.8'

services:
  back:
    build:
      context: ./back
    volumes:
      - ./back:/usr/src/app
      - ./back/data:/usr/src/app/data
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true